package: be_password
version: '3.0.0'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/be_password

requires:
    php: '>=8.3'
    redaxo: ^5.18.1
    packages:
        phpmailer: ^2
