package: be_password
version: '1.1.1'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/be_password

requires:
    redaxo: ^5.1.0
    packages:
        phpmailer: ^2
page:
    title: 'Passwort zurücksetzen'  
    perm: admin
