package: be_password
version: '2.1.0-dev-2025-02-11'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/be_password

requires:
    redaxo: ^5.17.0
    packages:
        phpmailer: ^2.0.0
